### DISCUSSION TITLE
add multiple backgtound-image  to each cell element

### DISCUSSION THREAD

**Discussion by Mahyab** [css-doodle/css-doodle#125] [General]
Hi there,
I want to import multiple different images to each <cell> with javascript API ( it's better to append  a img element :) ) 
but I can't access  <grid> or <cell> element with dom ( return null ) cause is not-standard dom element
is there any solution? 
thanks 

```css
<style>
  :root {
    --rule-a: (
      @grid: 8 / 100vw 100vh;
      grid-gap: 30px;
    );
    --rule-b: (
      /* background-image: url(./test4.jpg), url(./test.jpg); */
      background-position: center center;
      background-size: 100px 100px ;
      background-repeat: no-repeat;
    );
  }
</style>

<css-doodle class="doolde">
  @use: var(--rule-a), var(--rule-b);
  :container {
    background-color: #ddd;
  }
</css-doodle>
```

**Comment by Mahyab** [comment]
anyone there :) ?

**Comment by aolko** [comment]
any updates on this?

**Reply by yuanchuan** [reply]
Hi @Mahyab , @aolko 

I'm not sure I understand the problem. Did you mean to make the `background-image` dynamic and be able to change via JavaScript?

**Comment by yuanchuan** [comment]
One possible solution:

```css
<style>
  --rule-b: (
    /* ... */
    background: @var(--bgs);
  ); 
</style>

<css-doodle style="--bgs: url(./a.jpg), url(./b.jpg)">
  @use: var(--rule-a), var(--rule-b);
  :container {
    background-color: #ddd;
  }
</css-doodle>

<script>
  let doodle = document.querySelector('doodle');
  /* update css variables */
  doodle.style.setProperty('--bgs', 'url(./c.jpg), url(./d.jpg)');
</script>
```
