### ISSUE TITLE
Affect adjacent cells with hover

### ISSUE THREAD

**Issue by upavloff** [css-doodle/css-doodle#113]
Is it possible to affect adjacent cells inside hover?

either directly inside the hover something like
```css
  :hover + .cell + .cell -1 {
      background: #e6437d;
  }
```

Or on hover, change a variable's value for the specific cell and make changes with `@match`?
