### ISSUE TITLE
Idea: Bridge with custom properties 

### ISSUE THREAD

**Issue by yuanchuan** [css-doodle/css-doodle#25]
## The problem

Currently there is no way to share code between multiple `css-doodle` elements.  So that I can't define rules in one place.

## One possible solution

Inspired by the CSS Houdini, the rules can be put into variables inside normal styles.

```css
css-doodle {
  --rule: (
     color: @pick(red, blue);
  );
}
```

Yes that's a valid variable expression. So with that inside `css-doodle` element:

```css
<css-doodle>
  @use: var(--rule);

  /* can easily be rewritten */
  color: green;
</css-doodle>
```
