### ISSUE TITLE
Prettier incorrectly formats css

### ISSUE THREAD

**Issue by webberpuma** [css-doodle/css-doodle#42]
I tested this in vue:

```html
<template>
    <css-doodle use="var(--rule)"></css-doodle>
</template>
```
```javascript
<script>
import "css-doodle";
export default {};
</script>
```
```css
<style scoped>
css-doodle {
    --rule: (
      :doodle {
        @grid: 10x1 / 800px 600px; 
        background: #e5e5e5;
      }
    );
}
</style>
```

it renders good (in this case, just a grey background) 

but when i format the code using prettier, the css part becomes the following
```css
<style scoped>
css-doodle {
    --rule: (: doodle {@grid: 10x1 / 800px 600px; background: #e5e5e5;});
}
</style>
```

as you can see, there is a space between `:` and `doodle`, which breaks the code, it seems Prettier can not recognise the custom pseudo element/selector
