### ISSUE TITLE
Custom functions

### ISSUE THREAD

**Issue by yuanchuan** [css-doodle/css-doodle#55]
Example

```css
<css-doodle>
  @function fib: pos => {
    let a = 0, b = 1;
    while (0 < pos--) [a, b] = [b, a + b];
    return a;
  }

  ::after {
    content: @fib(10);
  }
</css-doodle>
 ```
