### ISSUE TITLE
Idea: @content

### ISSUE THREAD

**Issue by yuanchuan** [css-doodle/css-doodle#69]
Insert new elements.

```css

/* text node */
@content: 'some text';  

/* svg */
@content: @svg(

);

/* new doodle element */
@content: @doodle(

);
```

**Comment by yuanchuan** [comment]
How about using selectors?

```css
@svg {
  circle {
    x, y: 5;
    r: 4;
    fill: red;
  }
}
```

```html
<css-doodle>
  grid: 2 / 200px;

  @doodle {
     grid: 2 / 100%;
     background: @p(red, blue);
  }
</css-doodle>
```
