### ISSUE TITLE
Bug Report: `@p` custom properties in `@doodle`

### ISSUE THREAD

**Issue by jiangyijie27** [css-doodle/css-doodle#93]
```css
<css-doodle>
  <style>
    :doodle {
      @grid: 2x1;
      --colors: #000, #fff;
    }
    background: @doodle(
      @grid: 2 / 100%;
      --c-1: @p(--colors);
    );
  </style>
</css-doodle>
```

# What is expected?
`--c-1` is one of `#000, #fff`

# What is actually happening?
only first cell is right, `--c-1` is `--colors` in others.

<img width="516" alt="image" src="https://user-images.githubusercontent.com/7429808/171083291-19d9083a-44aa-43c2-bd50-e3d9d880dc4e.png">

<img width="349" alt="image" src="https://user-images.githubusercontent.com/7429808/171083251-549ad663-e655-4b65-b986-3689cf16bcba.png">
